apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: learning-project
  namespace: argocd
spec:
  description: Default project for general apps
  sourceRepos:
    - 'https://github.com/kbops/infra-lab.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
