apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: learning-project
  source:
    repoURL: https://github.com/kbops/infra-lab.git
    targetRevision: develop
    path: k8s-cargo-ship/helm/charts/app
    helm:
      releaseName: backend
      values: |
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
