apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: learning-project
  source:
    repoURL: https://github.com/kbops/infra-lab.git
    targetRevision: develop
    path: k8s-cargo-ship/helm/charts/monitoring
    helm:
      releaseName: monitoring
      values: |
        grafana:
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true