replicaCount: 2

image:
  repository: 106714502496.dkr.ecr.eu-central-1.amazonaws.com/cargo-ship
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.3" # latest is also acceptable.

DeploymentLabels:
  app: cargo-ship
  environment: production
  team: devops
  
podLabels:
  app: cargo-ship
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: flask-platform

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: a2fbc60a0e8ee4ff2b7bfa93b99efa2b-1264508776.eu-central-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: "0.1"
    memory: "200Mi"
  requests:
    cpu: "0.1"
    memory: "128Mi"

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 2
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

imagePullSecrets:
  - name: ecr-secret


nodeSelector: {}
autoscaling:
  enabled: false
serviceAccount:
  create: false
  name: ""
